// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package hcpv1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using TelemetryState within kubernetes types, where deepcopy-gen is used.
func (in *TelemetryState) DeepCopyInto(out *TelemetryState) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryState. Required by controller-gen.
func (in *TelemetryState) DeepCopy() *TelemetryState {
	if in == nil {
		return nil
	}
	out := new(TelemetryState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryState. Required by controller-gen.
func (in *TelemetryState) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TelemetryState_MetricsState within kubernetes types, where deepcopy-gen is used.
func (in *TelemetryState_MetricsState) DeepCopyInto(out *TelemetryState_MetricsState) {
	proto.Reset(out)
	proto.Merge(out, proto.Clone(in))
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryState_MetricsState. Required by controller-gen.
func (in *TelemetryState_MetricsState) DeepCopy() *TelemetryState_MetricsState {
	if in == nil {
		return nil
	}
	out := new(TelemetryState_MetricsState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryState_MetricsState. Required by controller-gen.
func (in *TelemetryState_MetricsState) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
