// Code generated by protoc-gen-grpc-inmem. DO NOT EDIT.

package pbconnectca

import (
	"context"

	grpc "google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/proto"
)

// compile-time check to ensure that the generator is implementing all
// of the grpc client interfaces methods.
var _ ConnectCAServiceClient = &InmemConnectCAServiceClient{}

// InmemConnectCAServiceClient implements the ConnectCAServiceClient interface by directly
// calling methods on the server implementation. This avoids unnecessary serialization
// and deserialization when the client and server are executing in the same process.
// The caveat to this performance optimization is that not all standard network
// based gRPC server options and client dialing options will be supported. The
// second caveat is that the caller needs to take care to ensure they don't modify
// shared data.
type InmemConnectCAServiceClient struct {
	srv ConnectCAServiceServer
}

func NewInmemConnectCAServiceClient(srv ConnectCAServiceServer) (ConnectCAServiceClient, error) {
	return &InmemConnectCAServiceClient{
		srv: srv,
	}, nil
}

func (c *InmemConnectCAServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	md, found := metadata.FromOutgoingContext(ctx)
	if found {
		ctx = metadata.NewIncomingContext(ctx, md)
	}

	out, err := c.srv.Sign(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *InmemConnectCAServiceClient) WatchRoots(ctx context.Context, in *WatchRootsRequest, opts ...grpc.CallOption) (ConnectCAService_WatchRootsClient, error) {
	md, found := metadata.FromOutgoingContext(ctx)
	if found {
		ctx = metadata.NewIncomingContext(ctx, md)
	}
	st := newInmemStreamFromServer[*WatchRootsResponse](ctx)
	go func() {
		st.CloseServerStream(c.srv.WatchRoots(in, st))
	}()

	return st, nil
}

// compile-time check to ensure that the generator is implementing all
// of the grpc client interfaces methods.
var _ ConnectCAServiceClient = CloningConnectCAServiceClient{}

// CloningConnectCAServiceClient implements the ConnectCAServiceClient interface by wrapping
// another implementation and copying all protobuf messages that pass through the client.
// This is mainly useful to wrap the InmemConnectCAServiceClient client to insulate users of that
// client from having to care about potential immutability of data they receive or having
// the server implementation mutate their internal memory.
type CloningConnectCAServiceClient struct {
	ConnectCAServiceClient
}

func NewCloningConnectCAServiceClient(client ConnectCAServiceClient) CloningConnectCAServiceClient {
	return CloningConnectCAServiceClient{
		ConnectCAServiceClient: client,
	}
}

func (c CloningConnectCAServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	in = proto.Clone(in).(*SignRequest)
	md, found := metadata.FromOutgoingContext(ctx)
	if found {
		ctx = metadata.NewIncomingContext(ctx, md)
	}

	out, err := c.ConnectCAServiceClient.Sign(ctx, in)
	if err != nil {
		return nil, err
	}

	return proto.Clone(out).(*SignResponse), nil
}

func (c CloningConnectCAServiceClient) WatchRoots(ctx context.Context, in *WatchRootsRequest, opts ...grpc.CallOption) (ConnectCAService_WatchRootsClient, error) {
	in = proto.Clone(in).(*WatchRootsRequest)
	st, err := c.ConnectCAServiceClient.WatchRoots(ctx, in)
	if err != nil {
		return nil, err
	}

	return newCloningStream(st), nil
}
